# Generated by Django 5.1.3 on 2024-11-18 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDemographics',
            fields=[
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestingECG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventricular_rate', models.IntegerField()),
                ('atrial_rate', models.IntegerField()),
                ('qrs_duration', models.IntegerField()),
                ('qt_interval', models.IntegerField()),
                ('qt_corrected', models.IntegerField()),
                ('r_axis', models.IntegerField()),
                ('t_axis', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientdemographics')),
            ],
        ),
        migrations.CreateModel(
            name='TestDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientdemographics')),
            ],
        ),
    ]
